export const FOOTBALL_TEAMS = {
  "Premier League (England)": [
    { name: "Arsenal", logo: "https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg" },
    { name: "Aston Villa", logo: "https://upload.wikimedia.org/wikipedia/en/9/9f/Aston_Villa_logo.svg" },
    { name: "Bournemouth", logo: "https://upload.wikimedia.org/wikipedia/en/e/e5/AFC_Bournemouth_%282013%29.svg" },
    { name: "Brentford", logo: "https://upload.wikimedia.org/wikipedia/en/2/2a/Brentford_FC_crest.svg" },
    { name: "Brighton", logo: "https://upload.wikimedia.org/wikipedia/en/f/fd/Brighton_%26_Hove_Albion_logo.svg" },
    { name: "Burnley", logo: "https://upload.wikimedia.org/wikipedia/en/6/62/Burnley_F.C._Logo.svg" },
    { name: "Chelsea", logo: "https://upload.wikimedia.org/wikipedia/en/c/cc/Chelsea_FC.svg" },
    { name: "Crystal Palace", logo: "https://upload.wikimedia.org/wikipedia/en/a/a2/Crystal_Palace_FC_logo_%282022%29.svg" },
    { name: "Everton", logo: "https://upload.wikimedia.org/wikipedia/en/7/7c/Everton_FC_logo.svg" },
    { name: "Fulham", logo: "https://upload.wikimedia.org/wikipedia/en/e/eb/Fulham_FC_%28shield%29.svg" },
    { name: "Liverpool", logo: "https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg" },
    { name: "Luton Town", logo: "https://upload.wikimedia.org/wikipedia/en/9/9d/Luton_Town_logo.svg" },
    { name: "Man City", logo: "https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg" },
    { name: "Man United", logo: "https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg" },
    { name: "Newcastle", logo: "https://upload.wikimedia.org/wikipedia/en/5/56/Newcastle_United_Logo.svg" },
    { name: "Nottm Forest", logo: "https://upload.wikimedia.org/wikipedia/en/d/d2/Nottingham_Forest_logo.svg" },
    { name: "Sheffield Utd", logo: "https://upload.wikimedia.org/wikipedia/en/9/9c/Sheffield_United_FC_logo.svg" },
    { name: "Tottenham", logo: "https://upload.wikimedia.org/wikipedia/en/b/b4/Tottenham_Hotspur.svg" },
    { name: "West Ham", logo: "https://upload.wikimedia.org/wikipedia/en/c/c2/West_Ham_United_FC_logo.svg" },
    { name: "Wolves", logo: "https://upload.wikimedia.org/wikipedia/en/f/fc/Wolverhampton_Wanderers.svg" }
  ],
  "La Liga (Spain)": [
    { name: "Alavés", logo: "https://upload.wikimedia.org/wikipedia/en/f/f8/Deportivo_Alaves_logo_%282020%29.svg" },
    { name: "Almería", logo: "https://upload.wikimedia.org/wikipedia/en/c/c5/UD_Almeria_logo.svg" },
    { name: "Athletic Club", logo: "https://upload.wikimedia.org/wikipedia/en/9/98/Club_Athletic_Bilbao_logo.svg" },
    { name: "Atlético Madrid", logo: "https://upload.wikimedia.org/wikipedia/en/f/f4/Atletico_Madrid_2017_logo.svg" },
    { name: "Barcelona", logo: "https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg" },
    { name: "Cádiz", logo: "https://upload.wikimedia.org/wikipedia/en/5/58/C%C3%A1diz_CF_logo.svg" },
    { name: "Celta Vigo", logo: "https://upload.wikimedia.org/wikipedia/en/1/12/RC_Celta_de_Vigo_logo.svg" },
    { name: "Getafe", logo: "https://upload.wikimedia.org/wikipedia/en/4/4c/Getafe_CF.svg" },
    { name: "Girona", logo: "https://upload.wikimedia.org/wikipedia/en/9/90/For_Girona_FC.svg" },
    { name: "Granada", logo: "https://upload.wikimedia.org/wikipedia/en/d/d5/Granada_CF_logo.svg" },
    { name: "Las Palmas", logo: "https://upload.wikimedia.org/wikipedia/en/8/8c/UD_Las_Palmas_logo.svg" },
    { name: "Mallorca", logo: "https://upload.wikimedia.org/wikipedia/en/e/e0/RCD_Mallorca_logo.svg" },
    { name: "Osasuna", logo: "https://upload.wikimedia.org/wikipedia/en/d/db/Osasuna_logo.svg" },
    { name: "Rayo Vallecano", logo: "https://upload.wikimedia.org/wikipedia/en/1/17/Rayo_Vallecano_logo.svg" },
    { name: "Real Betis", logo: "https://upload.wikimedia.org/wikipedia/en/1/13/Real_betis_logo.svg" },
    { name: "Real Madrid", logo: "https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg" },
    { name: "Real Sociedad", logo: "https://upload.wikimedia.org/wikipedia/en/f/f1/Real_Sociedad_logo.svg" },
    { name: "Sevilla", logo: "https://upload.wikimedia.org/wikipedia/en/3/3b/Sevilla_FC_logo.svg" },
    { name: "Valencia", logo: "https://upload.wikimedia.org/wikipedia/en/c/ce/Valenciacf.svg" },
    { name: "Villarreal", logo: "https://upload.wikimedia.org/wikipedia/en/7/70/Villarreal_CF_logo.svg" }
  ],
  "Bundesliga (Germany)": [
    { name: "Augsburg", logo: "https://upload.wikimedia.org/wikipedia/en/c/c5/FC_Augsburg_logo.svg" },
    { name: "Bayern Munich", logo: "https://upload.wikimedia.org/wikipedia/commons/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg" },
    { name: "Bochum", logo: "https://upload.wikimedia.org/wikipedia/commons/7/72/VfL_Bochum_logo.svg" },
    { name: "Bremen", logo: "https://upload.wikimedia.org/wikipedia/commons/b/be/SV-Werder-Bremen-Logo.svg" },
    { name: "Darmstadt", logo: "https://upload.wikimedia.org/wikipedia/en/8/87/SV_Darmstadt_98_Logo.svg" },
    { name: "Dortmund", logo: "https://upload.wikimedia.org/wikipedia/commons/6/67/Borussia_Dortmund_logo.svg" },
    { name: "Eintracht Frankfurt", logo: "https://upload.wikimedia.org/wikipedia/commons/0/04/Eintracht_Frankfurt_Logo.svg" },
    { name: "Freiburg", logo: "https://upload.wikimedia.org/wikipedia/en/6/6d/SC_Freiburg_logo.svg" },
    { name: "Heidenheim", logo: "https://upload.wikimedia.org/wikipedia/commons/9/9d/1._FC_Heidenheim_1846.svg" },
    { name: "Hoffenheim", logo: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Logo_TSG_Hoffenheim.svg" },
    { name: "Köln", logo: "https://upload.wikimedia.org/wikipedia/en/5/53/FC_Cologne_logo.svg" },
    { name: "Leverkusen", logo: "https://upload.wikimedia.org/wikipedia/en/5/59/Bayer_04_Leverkusen_logo.svg" },
    { name: "Mainz 05", logo: "https://upload.wikimedia.org/wikipedia/commons/9/9e/FSV_Mainz_05_Logo.svg" },
    { name: "Mönchengladbach", logo: "https://upload.wikimedia.org/wikipedia/commons/8/81/Borussia_M%C3%B6nchengladbach_logo.svg" },
    { name: "RB Leipzig", logo: "https://upload.wikimedia.org/wikipedia/en/0/04/RB_Leipzig_2014_logo.svg" },
    { name: "Stuttgart", logo: "https://upload.wikimedia.org/wikipedia/commons/e/eb/VfB_Stuttgart_1893_Logo.svg" },
    { name: "Union Berlin", logo: "https://upload.wikimedia.org/wikipedia/en/6/6c/1._FC_Union_Berlin_logo.svg" },
    { name: "Wolfsburg", logo: "https://upload.wikimedia.org/wikipedia/commons/c/ce/VfL_Wolfsburg_Logo.svg" }
  ],
  "Serie A (Italy)": [
    { name: "AC Milan", logo: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Logo_of_AC_Milan.svg" },
    { name: "Atalanta", logo: "https://upload.wikimedia.org/wikipedia/en/6/66/AtalantaBC.svg" },
    { name: "Bologna", logo: "https://upload.wikimedia.org/wikipedia/en/5/5b/Bologna_F.C._1909_logo.svg" },
    { name: "Cagliari", logo: "https://upload.wikimedia.org/wikipedia/en/6/61/Cagliari_Calcio_1920.svg" },
    { name: "Empoli", logo: "https://upload.wikimedia.org/wikipedia/en/a/a3/Empoli_FC_1920.svg" },
    { name: "Fiorentina", logo: "https://upload.wikimedia.org/wikipedia/en/b/ba/ACF_Fiorentina_2.svg" },
    { name: "Frosinone", logo: "https://upload.wikimedia.org/wikipedia/en/6/64/Frosinone_Calcio_logo.svg" },
    { name: "Genoa", logo: "https://upload.wikimedia.org/wikipedia/en/6/6c/Genoa_C.F.C._logo.svg" },
    { name: "Hellas Verona", logo: "https://upload.wikimedia.org/wikipedia/en/9/92/Hellas_Verona_FC_logo_%282020%29.svg" },
    { name: "Inter Milan", logo: "https://upload.wikimedia.org/wikipedia/commons/0/05/FC_Internazionale_Milano_2021.svg" },
    { name: "Juventus", logo: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Juventus_FC_2017_icon_%28black%29.svg" },
    { name: "Lazio", logo: "https://upload.wikimedia.org/wikipedia/en/c/ce/S.S._Lazio_badge.svg" },
    { name: "Lecce", logo: "https://upload.wikimedia.org/wikipedia/en/a/a0/U.S._Lecce_logo.svg" },
    { name: "Monza", logo: "https://upload.wikimedia.org/wikipedia/en/2/2e/AC_Monza_logo.svg" },
    { name: "Napoli", logo: "https://upload.wikimedia.org/wikipedia/commons/2/2d/SSC_Napoli_2007.svg" },
    { name: "Roma", logo: "https://upload.wikimedia.org/wikipedia/en/f/f7/AS_Roma_logo_%282017%29.svg" },
    { name: "Salernitana", logo: "https://upload.wikimedia.org/wikipedia/en/3/30/US_Salernitana_1919_logo.svg" },
    { name: "Sassuolo", logo: "https://upload.wikimedia.org/wikipedia/en/1/1c/US_Sassuolo_Calcio_logo.svg" },
    { name: "Torino", logo: "https://upload.wikimedia.org/wikipedia/en/2/2e/Torino_FC_Logo.svg" },
    { name: "Udinese", logo: "https://upload.wikimedia.org/wikipedia/en/c/ce/Udinese_Calcio_logo.svg" }
  ],
  "Ligue 1 (France)": [
    { name: "Brest", logo: "https://upload.wikimedia.org/wikipedia/en/0/05/Stade_Brestois_29_logo.svg" },
    { name: "Clermont Foot", logo: "https://upload.wikimedia.org/wikipedia/en/5/52/Clermont_Foot_63_logo.svg" },
    { name: "Le Havre", logo: "https://upload.wikimedia.org/wikipedia/en/a/ad/Le_Havre_AC_logo_%282023%29.svg" },
    { name: "Lens", logo: "https://upload.wikimedia.org/wikipedia/en/c/cc/RC_Lens_logo.svg" },
    { name: "Lille", logo: "https://upload.wikimedia.org/wikipedia/en/6/6f/Lille_OSC_2018_logo.svg" },
    { name: "Lorient", logo: "https://upload.wikimedia.org/wikipedia/en/2/25/FC_Lorient_logo_%282023%29.svg" },
    { name: "Lyon", logo: "https://upload.wikimedia.org/wikipedia/en/c/c6/Olympique_Lyonnais.svg" },
    { name: "Marseille", logo: "https://upload.wikimedia.org/wikipedia/commons/d/d8/Olympique_Marseille_logo.svg" },
    { name: "Metz", logo: "https://upload.wikimedia.org/wikipedia/en/0/02/FC_Metz_logo.svg" },
    { name: "Monaco", logo: "https://upload.wikimedia.org/wikipedia/en/b/ba/AS_Monaco_FC.svg" },
    { name: "Montpellier", logo: "https://upload.wikimedia.org/wikipedia/en/a/a8/Montpellier_HSC_logo.svg" },
    { name: "Nantes", logo: "https://upload.wikimedia.org/wikipedia/en/2/2b/FC_Nantes_logo.svg" },
    { name: "Nice", logo: "https://upload.wikimedia.org/wikipedia/en/2/2e/OGC_Nice_logo.svg" },
    { name: "PSG", logo: "https://upload.wikimedia.org/wikipedia/en/a/a7/Paris_Saint-Germain_F.C..svg" },
    { name: "Reims", logo: "https://upload.wikimedia.org/wikipedia/en/a/a6/Stade_de_Reims_Logo_%282020%29.svg" },
    { name: "Rennes", logo: "https://upload.wikimedia.org/wikipedia/en/9/9e/Stade_Rennais_FC.svg" },
    { name: "Strasbourg", logo: "https://upload.wikimedia.org/wikipedia/en/8/80/Racing_Club_de_Strasbourg_logo.svg" },
    { name: "Toulouse", logo: "https://upload.wikimedia.org/wikipedia/en/5/51/Toulouse_FC_2018_logo.svg" }
  ],
  "Eredivisie (Netherlands)": [
    { name: "Ajax", logo: "https://upload.wikimedia.org/wikipedia/en/7/79/Ajax_Amsterdam.svg" },
    { name: "AZ Alkmaar", logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/AZ_Alkmaar.svg" },
    { name: "Feyenoord", logo: "https://upload.wikimedia.org/wikipedia/en/e/e3/Feyenoord_logo.svg" },
    { name: "PSV Eindhoven", logo: "https://upload.wikimedia.org/wikipedia/en/0/05/PSV_Eindhoven.svg" },
    { name: "Twente", logo: "https://upload.wikimedia.org/wikipedia/en/8/86/FC_Twente_logo.svg" },
    { name: "Utrecht", logo: "https://upload.wikimedia.org/wikipedia/commons/9/93/FC_Utrecht.svg" }
  ],
  "Primeira Liga (Portugal)": [
    { name: "Benfica", logo: "https://upload.wikimedia.org/wikipedia/en/a/a2/SL_Benfica_logo.svg" },
    { name: "Boavista", logo: "https://upload.wikimedia.org/wikipedia/en/4/40/Boavista_F.C._logo.svg" },
    { name: "Braga", logo: "https://upload.wikimedia.org/wikipedia/en/7/79/S.C._Braga_logo.svg" },
    { name: "Porto", logo: "https://upload.wikimedia.org/wikipedia/en/f/f1/FC_Porto.svg" },
    { name: "Sporting CP", logo: "https://upload.wikimedia.org/wikipedia/en/e/e1/Sporting_Clube_de_Portugal_%28Logo%29.svg" },
    { name: "Vitória de Guimarães", logo: "https://upload.wikimedia.org/wikipedia/en/5/53/Vitoria_Guimaraes_logo.svg" }
  ],
  "Süper Lig (Turkey)": [
    { name: "Beşiktaş", logo: "https://upload.wikimedia.org/wikipedia/commons/2/20/Besiktas_jk.svg" },
    { name: "Fenerbahçe", logo: "https://upload.wikimedia.org/wikipedia/en/3/39/Fenerbah%C3%A7e.svg" },
    { name: "Galatasaray", logo: "https://upload.wikimedia.org/wikipedia/en/3/31/Galatasaray_Star_Logo.svg" },
    { name: "Trabzonspor", logo: "https://upload.wikimedia.org/wikipedia/en/8/82/Trabzonspor_logo.svg" },
    { name: "Başakşehir", logo: "https://upload.wikimedia.org/wikipedia/en/3/30/Istanbul_Basaksehir_Logo.svg" }
  ],
  "Scottish Premiership": [
    { name: "Aberdeen", logo: "https://upload.wikimedia.org/wikipedia/en/d/d4/Aberdeen_FC_logo.svg" },
    { name: "Celtic", logo: "https://upload.wikimedia.org/wikipedia/en/1/12/Celtic_FC.svg" },
    { name: "Hearts", logo: "https://upload.wikimedia.org/wikipedia/en/3/3a/Heart_of_Midlothian_FC_logo.svg" },
    { name: "Hibernian", logo: "https://upload.wikimedia.org/wikipedia/en/4/4b/Hibernian_FC_logo.svg" },
    { name: "Rangers", logo: "https://upload.wikimedia.org/wikipedia/en/4/43/Rangers_FC.svg" }
  ],
  "Saudi Pro League": [
    { name: "Al-Ahli", logo: "https://upload.wikimedia.org/wikipedia/en/b/b3/Al-Ahli_Saudi_FC_logo.svg" },
    { name: "Al-Ettifaq", logo: "https://upload.wikimedia.org/wikipedia/en/e/e0/Al_Ettifaq_FC_Logo.svg" },
    { name: "Al-Hilal", logo: "https://upload.wikimedia.org/wikipedia/en/d/d1/Al_Hilal_SFC_logo.svg" },
    { name: "Al-Ittihad", logo: "https://upload.wikimedia.org/wikipedia/en/e/e0/Al-Ittihad_Jeddah.svg" },
    { name: "Al-Nassr", logo: "https://upload.wikimedia.org/wikipedia/en/c/c5/Al_Nassr_FC_Logo.svg" },
    { name: "Al-Shabab", logo: "https://upload.wikimedia.org/wikipedia/en/3/3c/Al_Shabab_FC_Saudi_logo.svg" }
  ],
  "MLS (USA)": [
    { name: "Atlanta United", logo: "https://upload.wikimedia.org/wikipedia/en/2/27/Atlanta_United_FC_logo.svg" },
    { name: "Chicago Fire", logo: "https://upload.wikimedia.org/wikipedia/en/1/12/Chicago_Fire_Football_Club.svg" },
    { name: "Columbus Crew", logo: "https://upload.wikimedia.org/wikipedia/en/3/36/Columbus_Crew_logo.svg" },
    { name: "DC United", logo: "https://upload.wikimedia.org/wikipedia/en/4/43/DC_United_logo.svg" },
    { name: "Inter Miami", logo: "https://upload.wikimedia.org/wikipedia/en/5/5c/Inter_Miami_CF_logo.svg" },
    { name: "LA Galaxy", logo: "https://upload.wikimedia.org/wikipedia/en/c/c2/Los_Angeles_Galaxy_logo.svg" },
    { name: "LAFC", logo: "https://upload.wikimedia.org/wikipedia/en/d/da/Los_Angeles_FC_logo.svg" },
    { name: "New York City FC", logo: "https://upload.wikimedia.org/wikipedia/en/2/2a/New_York_City_FC_logo.svg" },
    { name: "NY Red Bulls", logo: "https://upload.wikimedia.org/wikipedia/en/2/29/New_York_Red_Bulls_logo.svg" },
    { name: "Seattle Sounders", logo: "https://upload.wikimedia.org/wikipedia/en/a/ae/Seattle_Sounders_FC_logo.svg" },
    { name: "Toronto FC", logo: "https://upload.wikimedia.org/wikipedia/en/b/b2/Toronto_FC_Logo.svg" }
  ],
  "Brasileirão (Brazil)": [
    { name: "Atlético Mineiro", logo: "https://upload.wikimedia.org/wikipedia/en/5/5f/Clube_Atl%C3%A9tico_Mineiro_crest.svg" },
    { name: "Botafogo", logo: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Botafogo_de_Futebol_e_Regatas_logo.svg" },
    { name: "Corinthians", logo: "https://upload.wikimedia.org/wikipedia/en/5/5a/Sport_Club_Corinthians_Paulista_crest.svg" },
    { name: "Flamengo", logo: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Flamengo_braz_logo.svg" },
    { name: "Fluminense", logo: "https://upload.wikimedia.org/wikipedia/en/9/91/Fluminense_FC_crest.svg" },
    { name: "Grêmio", logo: "https://upload.wikimedia.org/wikipedia/en/f/f1/Gr%C3%AAmio_FBPA.svg" },
    { name: "Internacional", logo: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Sport_Club_Internacional_logo.svg" },
    { name: "Palmeiras", logo: "https://upload.wikimedia.org/wikipedia/en/1/10/Palmeiras_logo.svg" },
    { name: "Santos", logo: "https://upload.wikimedia.org/wikipedia/commons/1/15/Santos_Logo.png" },
    { name: "São Paulo", logo: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Brasao_do_Sao_Paulo_Futebol_Clube.svg" },
    { name: "Vasco da Gama", logo: "https://upload.wikimedia.org/wikipedia/en/2/21/Club_de_Regatas_Vasco_da_Gama_logo.svg" }
  ],
  "International": [
    { name: "Argentina", logo: "https://upload.wikimedia.org/wikipedia/en/c/c1/Argentina_national_football_team_logo.svg" },
    { name: "Belgium", logo: "https://upload.wikimedia.org/wikipedia/en/f/f6/Royal_Belgian_FA_logo_2019.svg" },
    { name: "Brazil", logo: "https://upload.wikimedia.org/wikipedia/en/9/99/Brazilian_Football_Confederation_logo.svg" },
    { name: "Croatia", logo: "https://upload.wikimedia.org/wikipedia/en/7/77/Croatia_football_federation.svg" },
    { name: "England", logo: "https://upload.wikimedia.org/wikipedia/en/8/8b/England_national_football_team_crest.svg" },
    { name: "France", logo: "https://upload.wikimedia.org/wikipedia/en/8/86/France_national_football_team_seal.svg" },
    { name: "Germany", logo: "https://upload.wikimedia.org/wikipedia/en/e/e3/DFB-Logo_2014.svg" },
    { name: "Italy", logo: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Logo_della_Federazione_Italiana_Giuoco_Calcio.svg" },
    { name: "Japan", logo: "https://upload.wikimedia.org/wikipedia/en/8/84/Japan_national_football_team_crest.svg" },
    { name: "Mexico", logo: "https://upload.wikimedia.org/wikipedia/en/f/f7/Mexican_Football_Federation_logo.svg" },
    { name: "Netherlands", logo: "https://upload.wikimedia.org/wikipedia/en/7/78/Netherlands_national_football_team_logo.svg" },
    { name: "Portugal", logo: "https://upload.wikimedia.org/wikipedia/en/5/5f/Portuguese_Football_Federation.svg" },
    { name: "Spain", logo: "https://upload.wikimedia.org/wikipedia/en/3/31/Spain_National_Football_Team_badge.png" },
    { name: "USA", logo: "https://upload.wikimedia.org/wikipedia/en/a/ac/U.S._Soccer_Federation_logo_2016.svg" }
  ]
};